apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
  namespace: auth-system
data:
  config.yaml: |
    issuer: https://dex.rahmatawe.com
    web:
      http: 0.0.0.0:5556
    frontend:
      theme: custom
    telemetry:
      http: 0.0.0.0:5558
    staticClients:
    - id: rahmatawe-app
      redirectURIs:
      - 'https://kubectl.rahmatawe.com/callback'
      - 'http://dashboard.rahmatawe.com/oauth2/callback'
      name: 'rahmatawe-app'
      secret: XmT7EHo27skGchX0yLQNTYXibm3aNkx5
    connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: ldap.rahmatawe.com:389
        insecureNoSSL: true
        insecureSkipVerify: true
        bindDN: CN=admin,DC=rahmatawe,DC=com
        bindPW: Elpsy12! #Add Administrator password
        usernamePrompt: SSO Username
        userSearch:
          baseDN: OU=People,DC=rahmatawe,DC=com
          filter: "(objectClass=person)"
          username: mail
          idAttr: uid
          emailAttr: mail
          nameAttr: cn
        groupSearch:
          baseDN: OU=Groups,DC=rahmatawe,DC=com
          filter: "(objectClass=groupOfNames)"
          userAttr: DN
          groupAttr: member
          nameAttr: cn
    oauth2:
      skipApprovalScreen: true
    storage:
      type: kubernetes
      config:
        inCluster: true

