apiVersion: v1
kind: ConfigMap
metadata:
  name: gangway
  namespace: auth-system
data:
  gangway.yaml: |
    clusterName: "kubernetes"
    apiServerURL: "https://10.54.54.10:6443"
    authorizeURL: "https://dex.rahmatawe.com/auth"
    tokenURL: "https://dex.rahmatawe.com/token"
    clientID: "rahmatawe-app"
    clientSecret: "XmT7EHo27skGchX0yLQNTYXibm3aNkx5"
    redirectURL: "https://kubectl.rahmatawe.com/callback"
    scopes: ["openid", "profile", "email","groups", "offline_access"]
    usernameClaim: "email"
    emailClaim: "email"
    trustedCAPath: "/cacerts/tls.crt"
